/**
 * Obsidian formatter for meeting summaries with wikilink injection.
 * NO transcripts — summaries only.
 */

import { invoke } from '@tauri-apps/api/core';
import { ModelConfig } from '@/services/configService';

export interface ExtractedEntities {
  people: string[];
  orgs: string[];
  priorities: string[];
  decisions: string[];
}

export interface MeetingRecord {
  meetingId: string;
  meetingTitle: string;
  meetingDate: string;   // YYYY-MM-DD
  summaryText: string;
}

export interface BackfillProgress {
  total: number;
  completed: number;
  skipped: number;
  failed: number;
  currentTitle: string;
}

/**
 * Calls Databricks model to extract entities from summary text.
 * Returns structured entities for wikilink injection.
 */
export async function extractEntities(
  summaryText: string,
  workspaceUrl: string,
  endpointName: string,
  token: string
): Promise<ExtractedEntities> {
  console.log('[Obsidian] Extracting entities...');
  
  const prompt = `Extract entities from this meeting summary.
Return ONLY valid JSON, no preamble, no markdown fences.

{
  "people": ["Full Name"],
  "orgs": ["Organisation or Team Name"],
  "priorities": ["Project or Initiative Name"],
  "decisions": ["Short decision under 8 words"]
}

Rules:
- people: full names only
- orgs: teams, companies, business units
- priorities: projects, initiatives, workstreams
- decisions: concrete decisions made, brief
- Return empty arrays if none found

Summary:
${summaryText}`;

  try {
    const response = await fetch(
      `${workspaceUrl}/serving-endpoints/${endpointName}/invocations`,
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          messages: [{ role: 'user', content: prompt }],
        }),
      }
    );
    
    if (!response.ok) {
      throw new Error(`Entity extraction HTTP ${response.status}`);
    }
    
    const data = await response.json();
    const text = data.choices?.[0]?.message?.content || '{}';
    const clean = text.replace(/```json|```/g, '').trim();
    const entities = JSON.parse(clean) as ExtractedEntities;
    
    console.log('[Obsidian] Entities extracted:', entities);
    return entities;
    
  } catch (e) {
    console.warn('[Obsidian] Entity extraction failed, no wikilinks:', e);
    return { people: [], orgs: [], priorities: [], decisions: [] };
  }
}

/**
 * Injects [[wikilinks]] into summary text for extracted entities.
 */
export function injectWikilinks(
  text: string,
  entities: ExtractedEntities
): string {
  let result = text;
  
  // Longest names first to avoid partial replacements
  const all = [
    ...entities.people,
    ...entities.orgs,
    ...entities.priorities,
  ].sort((a, b) => b.length - a.length);
  
  for (const entity of all) {
    if (!entity?.trim()) continue;
    const escaped = entity.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const regex = new RegExp(`\\b${escaped}\\b`, 'g');
    result = result.replace(regex, `[[${entity}]]`);
  }
  
  return result;
}

/**
 * Formats summary and entities into a full Obsidian Markdown note.
 * NO transcript section — summaries only.
 */
export function formatObsidianNote(params: {
  meetingTitle: string;
  meetingDate: string;
  duration: string;
  summaryWithWikilinks: string;
  entities: ExtractedEntities;
}): string {
  const { meetingTitle, meetingDate, duration, summaryWithWikilinks, entities } = params;
  
  const attendees = entities.people.length > 0
    ? entities.people.map(p => `[[${p}]]`).join(', ')
    : '_Not identified_';
  
  const priorities = entities.priorities.length > 0
    ? entities.priorities.map(p => `- [[${p}]]`).join('\n')
    : '_None identified_';
  
  const decisions = entities.decisions.length > 0
    ? entities.decisions.map(d => `- ${d}`).join('\n')
    : '_None recorded_';
  
  return `---
date: ${meetingDate}
duration: ${duration}
attendees: [${entities.people.map(p => `"${p}"`).join(', ')}]
orgs: [${entities.orgs.map(o => `"${o}"`).join(', ')}]
tags: [meeting, auto-generated]
---

# ${meetingTitle}

**Date:** ${meetingDate}  
**Duration:** ${duration}  
**Attendees:** ${attendees}

## Summary

${summaryWithWikilinks}

## Key Priorities

${priorities}

## Decisions

${decisions}

---
_Generated by Meetily on ${meetingDate}_
`;
}

/**
 * Core sync helper — used by ALL three flows (auto, backfill, manual save).
 * NO transcript parameter.
 */
export async function syncMeetingToObsidian(params: {
  meetingTitle: string;
  meetingDate: string;
  duration: string;
  summaryText: string;
  modelConfig: ModelConfig;
  token: string;
  vaultPath: string;
}): Promise<void> {
  const { meetingTitle, meetingDate, duration, summaryText, modelConfig, token, vaultPath } = params;
  
  console.log('[Obsidian] Syncing:', meetingTitle);
  
  let entities: ExtractedEntities = {
    people: [], orgs: [], priorities: [], decisions: []
  };
  
  // Extract entities only if Databricks is configured
  if (
    modelConfig.provider === 'databricks' &&
    modelConfig.model &&
    token
  ) {
    const workspaceUrl = modelConfig.databricksWorkspaceUrl?.trim() || '';
    if (workspaceUrl) {
      entities = await extractEntities(
        summaryText, workspaceUrl, modelConfig.model, token
      );
    }
  }
  
  const summaryWithWikilinks = injectWikilinks(summaryText, entities);
  
  const noteContent = formatObsidianNote({
    meetingTitle,
    meetingDate,
    duration,
    summaryWithWikilinks,
    entities,
  });
  
  await invoke('write_obsidian_note', {
    vaultPath,
    meetingTitle,
    meetingDate,
    meetingDuration: duration,
    summaryText: noteContent,
  });
  
  console.log('[Obsidian] Sync complete:', meetingTitle);
}

/**
 * Renames an existing vault file when meeting title changes.
 */
export async function renameObsidianNote(params: {
  vaultPath: string;
  meetingDate: string;
  oldTitle: string;
  newTitle: string;
}): Promise<boolean> {
  const { vaultPath, meetingDate, oldTitle, newTitle } = params;
  
  if (oldTitle.trim() === newTitle.trim()) {
    console.log('[Obsidian] Title unchanged, no rename needed');
    return false;
  }
  
  console.log('[Obsidian] Renaming vault file:', { from: oldTitle, to: newTitle });
  
  const renamed = await invoke<boolean>('rename_obsidian_note', {
    vaultPath, meetingDate, oldTitle, newTitle,
  });
  
  console.log('[Obsidian] Rename result:', renamed);
  return renamed;
}

/**
 * Backfills all existing meetings with summaries to Obsidian vault.
 */
export async function backfillMeetingsToObsidian(
  vaultPath: string,
  modelConfig: ModelConfig,
  token: string,
  onProgress: (progress: BackfillProgress) => void
): Promise<BackfillProgress> {
  console.log('[Obsidian] Starting backfill...');
  
  const meetings = await invoke<MeetingRecord[]>(
    'get_all_meetings_with_summaries'
  );
  
  const progress: BackfillProgress = {
    total: meetings.length,
    completed: 0,
    skipped: 0,
    failed: 0,
    currentTitle: '',
  };
  
  for (const meeting of meetings) {
    progress.currentTitle = meeting.meetingTitle;
    onProgress({ ...progress });
    
    try {
      // Skip if note already exists in vault
      const exists = await invoke<boolean>('obsidian_note_exists', {
        vaultPath,
        meetingDate: meeting.meetingDate,
        meetingTitle: meeting.meetingTitle,
      });
      
      if (exists) {
        console.log('[Obsidian] Skipping (exists):', meeting.meetingTitle);
        progress.skipped++;
        onProgress({ ...progress });
        continue;
      }
      
      await syncMeetingToObsidian({
        meetingTitle: meeting.meetingTitle,
        meetingDate: meeting.meetingDate,
        duration: 'Unknown',
        summaryText: meeting.summaryText,
        modelConfig,
        token,
        vaultPath,
      });
      
      progress.completed++;
      
    } catch (e) {
      console.error('[Obsidian] Failed:', meeting.meetingTitle, e);
      progress.failed++;
    }
    
    onProgress({ ...progress });
    
    // Throttle Databricks API calls
    if (modelConfig.provider === 'databricks') {
      await new Promise(resolve => setTimeout(resolve, 800));
    }
  }
  
  console.log('[Obsidian] Backfill complete:', progress);
  return progress;
}
